apiVersion: v1
kind: Pod
metadata:
  name: pod-seagate
  namespace: demo
spec:
  containers:
  - image: gcr.io/google-containers/busybox:latest
    name: theapp
    volumeMounts:
    - mountPath: /vol
      name: volume-seagate
    command: [ "sleep", "1000" ]
  volumes:
  - name: volume-seagate
    persistentVolumeClaim:
      claimName: pvc-seagate
