apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-seagate
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: storageclass-seagate
  resources:
    requests:
      storage: 1Gi
