apiVersion: v1
kind: Secret
metadata:
  name: seagate-enclosure001
  namespace: seagate
type: Opaque
data:
  apiAddress: aHR0cDovLzEwLjIzNS4yMTIuMTk3 # base64 encoded api address http://10.235.212.197, ip only is MTAuMjM1LjIxMi4xOTc=
  username: bWFuYWdl # base64 encoded username
  password: IW1hbmFnZQ== # base64 encoded password
