apiVersion: v1
kind: Secret
metadata:
  name: seagate-enclosure001
  namespace: seagate
type: Opaque
data:
  apiAddress: aHR0cDovLzE5Mi4xNjguMC4x # base64 encoded api address http://192.168.0.1
  username: dXNlcg== # base64 encoded username
  password: cGFzc3dvcmQ= # base64 encoded password
