apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: snapshot-seagate
  namespace: demo
spec:
  volumeSnapshotClassName: snapshotclass-seagate
  source:
    persistentVolumeClaimName: pvc-seagate
